FaceModelConfig:
  _target_: polygen.polygen_config.FaceModelConfig
  accelerator: "ddp"
  dataset_path: "/coc/scratch/aahluwalia30/shapenet/shapenetcore/shapenet-lite-class-conditional"
  batch_size: 12
  training_split: 0.80
  val_split: 0.10
  apply_random_shift: True
  shuffle_vertices: True
  encoder_config: 
    {
      "hidden_size": 256, 
      "fc_size": 1024, 
      "num_layers": 12, 
      "dropout_rate": 0.2
    }
  decoder_config: 
    {
      "hidden_size": 256, 
      "fc_size": 1024, 
      "num_layers": 12, 
      "dropout_rate": 0.2
    }
  class_conditional: False
  num_classes: 4
  decoder_cross_attention: True
  use_discrete_vertex_embeddings: True
  quantization_bits: 8
  max_seq_length: 2800
  learning_rate: 3e-4
  step_size: 5000
  gamma: 0.995
  training_steps: 200000